### PR TITLE
added german keyboard layout

### PR DESCRIPTION
**Pull request by Henry-Jones**

### CODE REVIEW

**Comment by Henry-Jones** [comment]
Hello, I guess this is far beyond my knowledge of Phyton and the micro Phyton in particular. I can follow the idea technology wise but my pull request was not more than a quick "hack" from a usually C# and Powershell programmer. So go ahead and build it in a Python fitting fashion. ;)

**Comment by dherrada** [comment]
@Henry-Jones Sure thing. I was actually just about to get started on that.

**Comment by dhalbert** [comment]
One issue is that the current HID is a very tight fit as a frozen library on SAMD21 boards right now; any new code (refactored or not) is probably going to overflow flash. We might consider adding keyboard layouts in separate libraries. A common superclass might be able to fit.

**Comment by kattni** [comment]
I agree with Dan. I'm closing this PR for now as we cannot add another keyboard layout reasonably in this fashion. Dan created an issue and linked it to this PR. Hopefully someone picks it up - Dylan is away for a bit and will not be able to pick it up anytime soon.

@Henry-Jones If you're interested in looking into the suggested solution, please let us know. It sounds like you're not as comfortable in Python as other languages, so I understand if you're not interested.

**Pull request closed without merging**
