### PR TITLE
fix gamepad examples

### LINKED ISSUE #71: Fix gamepad examples
`gamepad.py` is no longer in the base library, because the gamepad device was removed from CircuitPython 7.0.0.

- Rename `examples/gamepad.py` to `examples/hid_gamepad.py` or similar, because `gamepad.py` overlaps with the `gamepad` built-in module.
- Fix or remove the gamepad-based examples.
- Add documentation about how to add a gamepad device to CircuitPython 7.0.0, or refer to a guide.

### PR DESCRIPTION
**Pull request by FoamyGuy**
resolves #71 

The changes in this PR: 
- rename `gamepad.py` to `hid_gamepad.py`
- change the usage imports in the other examples to match the new name
- add note and guide link about needing to setup the gamepad HID device
- fix the `adafruit_seesaw` import. During testing I noticed that it was not able to be initialized properly using the code that was there before.

I tested `hid_gamepad.py` and the two examples that make use of it on a Feather RP2040 with 7.0.0 alpha6

### CODE REVIEW

**Comment by FoamyGuy** [comment]
Hmmm, `pre-commit` passed successfully when I ran it locally:
```
❯ pre-commit run --all-files
black....................................................................Passed
reuse....................................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
pylint (library code)....................................................Passed
pylint (examples code)...................................................Passed
```
Perhaps there are differing versions of pylint or something else different about my environment. I'll try to look into why it failed in the actions check.

**Comment by FoamyGuy** [comment]
Indeed the PyLint failure seems to be related to version `2.10` of PyLint which was released a few hours ago https://github.com/PyCQA/pylint/releases/tag/v2.10.0

I installed that version locally and now my local pre-commit fails the same way that the one inside the actions run is. 

To verify I installed version `2.9.6` which was the previous release version and with that version pre-commit runs and completes successfully.

**Comment by FoamyGuy** [comment]
More information about the pylint failure can be found here: https://github.com/PyCQA/pylint/issues/4883

**Comment by dhalbert** [comment]
pylint 2.10.1 with a fix for this (https://github.com/PyCQA/pylint/pull/4884) has been released on pypi.org.

**Review by dhalbert — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
