### PR TITLE
Enable true 16-bit codes to work

### PR DESCRIPTION
**Pull request by zeevro**
I fixed the code so that codes above 0xFF will work. Only the low byte of the code was used before.

### CODE REVIEW

**Comment by dhalbert** [comment]
Thank you for finding this issue and submitting a fix. I've done it a slightly different way: could you test? See https://github.com/adafruit/Adafruit_CircuitPython_HID/pull/23.

**Comment by zeevro** [comment]
Will test it tomorrow. Thanks.

**Comment by zeevro** [comment]
Your fix seems to work. Thanks :)

**Comment by dhalbert** [comment]
#23 substitutes for this. Thanks!

**Pull request closed without merging**
