### PR TITLE
Fix #117: Rework host USB ready timeout

### LINKED ISSUE #117: usb_hid behaviour at boot..
### CircuitPython version

```python
Adafruit CircuitPython 8.0.5 on 2023-03-31; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
import usb_midi
import usb_cdc
import usb_hid
import storage

usb_cdc.disable()   # Disable both serial devices.
usb_midi.disable()  # Disable mini
usb_hid.enable((usb_hid.Device.KEYBOARD, usb_hid.Device.CONSUMER_CONTROL))   # Enable just KEYBOARD and CONSUMER CONTROL
```

### Behavior

...

### Description

I have a project using circuitpython to provide a usb HID device (keyboard), however come up with some strange operating behaviour.

When connect a linux host (raspbian rpi4) at boot, the device is detected however doesnt function as a keyboard. Removing the usb connection and replugging back in, the device works as expected.

If I automount the CIRCUITPY disk at boot, then the device will work as expected also.

Is there a way to have this device function as expected without having to mount the usb-storage device?

dmesg output from boot
```
[    2.745421] usb 1-1.4: new full-speed USB device number 5 using xhci_hcd
[    2.892517] usb 1-1.4: New USB device found, idVendor=239a, idProduct=80f4, bcdDevice= 1.00
[    2.892543] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.892561] usb 1-1.4: Product: Pico
[    2.892578] usb 1-1.4: Manufacturer: Raspberry Pi
[    2.892594] usb 1-1.4: SerialNumber: E66118C4173BBA26
[    2.900386] usb-storage 1-1.4:1.0: USB Mass Storage device detected
[    2.901230] scsi host0: usb-storage 1-1.4:1.0
[    2.910112] input: Raspberry Pi Pico Keyboard as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.1/0003:239A:80F4.0003/input/input2
[    2.976415] input: Raspberry Pi Pico Consumer Control as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.1/0003:239A:80F4.0003/input/input3

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eightycc**
Resolves #117.

### CODE REVIEW

**Comment by uzi18** [comment]
@eightycc is it related also to boot keyboard?
Could try to test it.

**Comment by eightycc** [comment]
@dhalbert Over to you for review!

**Comment by eightycc** [comment]
@uzi18 Fixes original issue in #117. Give it a try if you like. Tested here with an RP 4 host and it works.

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thanks for working on this. A few ideas and q's:

1. Did you try spinning on  `supervisor.runtime.usb_connected` to see if that worked out instead of trying the no-op sends? The advantage of that is that the connection testing could then be refactored into a single common routine, to reduce code size. It could be made part of `find_device()`, so that not only does it have to find the device, but it also has to test connectivity.

2. Instead of a fixed timeout, each `__init__()` could take an optional argument `, timeout: int = 20)`. That would allow quicker failures for people who don't need to wait 20 seconds. (20 seconds is a _long_ time). The timeout could get passed to `find_device()` if 1. is implemented.

3. A better error message: `raise OSError("Failed to  initialize HID device. Are you connected?")`. Of course, you're not connected, no one is going to see this :) .

**Comment by eightycc** [comment]
@dhalbert Thanks for the thoughtful review.

1. Embarrassed to say I didn't. I can see the value of factoring the code, so I'll give it a try.
2. Good idea. I'll do it.
3. Thought about a more verbose message and then realized the same thing you did, the user won't be able to see it unless they've taken steps like I did by building a custom CP with UART debug. Shall we keep it short and sweet to save precious bytes?

**Comment by dhalbert** [comment]
> 3\. Thought about a more verbose message and then realized the same thing you did, the user won't be able to see it unless they've taken steps like I did by building a custom CP with UART debug. Shall we keep it short and sweet to save precious bytes?

If there's just one mention, it could be longer, because it will be in only .mpy (especially if frozen). I realized it will show up on boards with displays even if they don't have USB connectivity, so making it a bit more helpful will help at least some of the time.

**Comment by eightycc** [comment]
@dhalbert I've made the updates you requested. CI is failing with due to my import of `supervisor`, but the code definitely works. My bug or CI?

```
Warning, treated as error:
autodoc: failed to import module 'keyboard' from module 'adafruit_hid'; the following exception was raised:
No module named 'supervisor'
```

**Comment by eightycc** [comment]
@dhalbert Also, I should have given the `timeout` parm in find_device a default, otherwise it's going to break existing user code. I'll fix that too when I hear back from you.

**Comment by dhalbert** [comment]
> CI is failing due to my import of `supervisor`

Hmm, this is because `adafruit_blinka` does not have any support for `supervisor`. It _does_ have support for `usb_hid` via the usb_gadget Linux kernel driver. 

We could add limited support of `supervisor` to Blinka. That is another project, though maybe a small one. If a Linux host is using `usb_hid` in the same way to emulate being a USB device, it will encounter the same issue that CircuitPython might encounter, of the USB host not being ready.

In the meantime, you could guard the `import supervisor` and just not test `supervisor.runime.usb_connected` in `find_device()` right now if `supervisor` is not available. Maybe just delay for a second or too, because that's what the old code did. The number of people using the `usb_gadget` capability is small, so they could do some special coding in the meantime or just not update their `adafruit_hid` library.

@makermelissa Do you have any opinion about adding limited `supervisor` support to Blinka, specifically `supervisor.runtime.usb_connected`? I see no mention of `supervisor` in the Blinka issues. I will look to see if `usb_gadget` has a simple way to test for being connected, but I have no experience with it.

**Review by dhalbert — COMMENTED** [review]
Thanks! Looks good -- did you test in the two cases of cold and warm RPi host startup?

Why did you lengthen the timeout to 45 seconds? That is a really long time, more than the 15 seconds you were seeing during initial testing. If someone needs a timeout that long, they could explicitly supply it.

**Comment by eightycc** [comment]
Yes, I did increase the timeout to 45 seconds. The reason is that the PI 4 was actually taking about 40 seconds, but I didn't see it because there's another timeout deeper in the USB code that was adding a second for every one of my seconds. Yikes!

**Comment by eightycc** [comment]
@dhalbert Yes, I did test hot and cold. Hot starts up immediately.

I saw the guarding of other imports and had wondered about it. Now I know that Blinka is part of the ecosystem. If I delay say 1 or 2 seconds in the Blinka case, it should just fail like it used to in all cases with a `USB busy` throw, so no harm done and no need not to update the library for Blinka.

Since the timeout interval won't affect normal usage, I'm not too worried about a long timeout in the failing case. But, it's your call. Timeouts and watchdogs are both bears to get right!

**Comment by dhalbert** [comment]
I just want to confirm my understanding of the use case. Let's suppose you have an RPi with, say, a MacroPad plugged in, and also a conventional keyboard and a USB stick drive.

When you power up the RPi, can it take up to 40 seconds for it to be responsive to the keyboard, and to mount the USB drive? Is this an RPi 4 or something that boots more slowly?

**Comment by eightycc** [comment]
> When you power up the RPi, can it take up to 40 seconds for it to be responsive to the keyboard, and to mount the USB drive? Is this an RPi 4 or something that boots more slowly?

Yes, the RPi 4 takes that long to get to USB enumeration. I'm testing with a stock 4G model loaded with an up to date but unmodified Raspbian 32-bit image. On POR, it's got gobs o' blobs that it has to load up before it even gets to the kernel.

The use case is any USB device that is already plugged in at POR. In the case of the OP on the issue, it's an Pico bridging an old scan-style Amiga keyboard to USB.

**Comment by dhalbert** [comment]
Another idea is if the timeout is `None`, to wait indefinitely. Maybe that should actually be the default. That's the way hardware keyboards, etc. work. They won't timeout. Then we don't need to get into testing "worst case" things.

**Comment by eightycc** [comment]
@dhalbert Double-plus good on the timeout `None` idea. Consider it done!

Shall I wait for https://github.com/adafruit/Adafruit_Blinka/issues/711 or plow ahead with the guard? Or maybe you'd like me to write a pull for Blinka?

**Comment by dhalbert** [comment]
I started looking at Blinka and usb_gadget but didn't get very far into it, and I have other things i need to work on at the moment.

You could look at what it would take in Blinka, but we don't have to hold this up, since you have a workaround without it. We can always revise this library again.

**Comment by eightycc** [comment]
@dhalbert Over to you for what should be a final review! I'm digging into Blinka now and will update https://github.com/adafruit/Adafruit_Blinka/issues/711 when I've got additional status.

**Review by dhalbert — APPROVED** [review]
Thanks for your perseverance through the review process. I think this is a significant improvement to the current semantics.

In discord someone mentioned that `supervisor.runtime.usb_connected` may not detect _disconnection_ properly: it might still return True. However, that is not this library's problem, and we can investigate that separately.

I am going to make this a major revision change, because the semantics have changed, since the devices now by default wait indefinitely instead of only a second or two.

**Comment by uzi18** [comment]
where to get mpy files ?

**Comment by eightycc** [comment]
> where to get mpy files ?

Just grab the `adafruit_hid` folder from this project and put it in your `lib` folder. The `.mpy` version will follow  when this is integrated into the CP library bundle. @dhalbert says at the next major revision, so I take that to mean CP 9.0.

**Comment by dhalbert** [comment]
The new release, 6.0.0, will go in the daily bundle tonight.

**Comment by uzi18** [comment]
@dhalbert have some questions about CP,  must open new issue for this or ask somewhere else?

**Comment by dhalbert** [comment]
@uzi18 If you have general use questions, ask in discord, https://adafru.it/discord, channel #help-with-circuitpython. That is community-based support with some staff people hanging out. Or you can open a thread in our forums, which is "official" support: https://forums.adafruit.com/viewforum.php?f=60. For a dialog, discord works well.

**Pull request merged**
