### PR TITLE
Add french layout (with example)

### PR DESCRIPTION
**Pull request by maditnerd**

### CODE REVIEW

**Comment by dhalbert** [comment]
Hi, this is very nice. Sadly, this library is frozen into various builds (especially CPX), and adding significantly more code to the library makes the frozen version of the library no longer fit on those builds.

This issue came up with a previous PR: see #46 and #53. If the KeyboardLayout class is refactored into a common class and then language specific pieces (either by subclassing or composition), then we can create new libraries for other keyboard layouts. They would be in separate repos.

**Comment by maditnerd** [comment]
OK, I'll wait until **KeyboardLayout class** is refactored. 👍

In the meantime, if someone want to use the french layout
You can find **Adafruit_hid library (with french layout only) 6.x-mpy-20201105** here. 
[Adafruit_HID FR](https://github.com/usini/CircuitPython_Exemples/tree/main/clavier_fr_tweet/lib/adafruit_hid)

I'm working on examples for Circuit Python in french for my workshop at Labsud (that's why I need it)
https://github.com/usini/CircuitPython_Exemples
I'll probably translates these, afterwards.

**Comment by kattni** [comment]
Closing this for now. We can revisit it once we have refactored things.

**Comment by AngainorDev** [comment]
Gave a try at refactoring with ancestor and including your french layout.
Working but likely to need further work
https://github.com/AngainorDev/Adafruit_CircuitPython_HID/tree/layouts/adafruit_hid

**Pull request closed without merging**
